/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { memoryStore } from "../MemoryStore";
import { semanticMemory } from "../SemanticMemory";
import { conversationMemory } from "../ConversationMemory";
import { workflowMemory } from "../WorkflowMemory";
import { memoryGraph } from "../MemoryGraph";
import { memoryRanker } from "../MemoryRanker";
import { memoryRetriever } from "../MemoryRetriever";
import { memoryCompressor } from "../MemoryCompressor";
import { contextBuilder } from "../ContextBuilder";
import { memoryManager } from "../MemoryManager";
import { memoryEngine } from "../MemoryEngine";

async function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`Assertion Failed: ${message}`);
  }
  console.log(`  ✓ ${message}`);
}

export async function runAllMemoryTests(): Promise<void> {
  console.log("\n============================================================");
  console.log("RUNNING UNIVERSAL MEMORY ENGINE TEST SUITE");
  console.log("============================================================\n");

  try {
    // Clear any persistent memories for fresh clean test state
    memoryStore.clear();
    memoryGraph.clear();

    // ------------------------------------------------------------
    // TEST 1: Memory Store CRUD operations
    // ------------------------------------------------------------
    console.log("1. Running Memory Store CRUD tests...");
    
    const node1 = memoryStore.save({
      type: "short",
      content: "Short-term active thought context",
      tags: ["active", "test"],
      importance: 7,
      confidence: 0.9,
    });

    await assert(node1 !== undefined, "MemoryStore: Successfully created a memory node.");
    await assert(node1.id.startsWith("mem_"), "MemoryStore: Autogenerated ID matching standard format.");
    await assert(node1.content === "Short-term active thought context", "MemoryStore: Content saved successfully.");
    await assert(node1.importance === 7, "MemoryStore: Importance scale is preserved.");
    
    const fetchedNode = memoryStore.get(node1.id);
    await assert(fetchedNode !== undefined, "MemoryStore: Retrieved saved node by ID.");
    await assert(fetchedNode?.usageCount === 1, "MemoryStore: Usage count increments upon fetch.");

    const deleted = memoryStore.delete(node1.id);
    await assert(deleted === true, "MemoryStore: Deleted node successfully.");
    
    const fetchedDeleted = memoryStore.get(node1.id);
    await assert(fetchedDeleted === undefined, "MemoryStore: Deleted node is no longer retrievable.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 2: Semantic Memory & Cosine Similarity
    // ------------------------------------------------------------
    console.log("2. Running Semantic Memory & Embeddings tests...");
    
    const textA = "Multi-agent orchestration coordinates intelligent systems.";
    const textB = "Intelligent multi-agent systems require fine-tuned routing.";
    const textC = "Cooking delicious recipes with fresh organic vegetables.";

    const embedA = await semanticMemory.getEmbedding(textA);
    const embedB = await semanticMemory.getEmbedding(textB);
    const embedC = await semanticMemory.getEmbedding(textC);

    await assert(Array.isArray(embedA) && embedA.length === 128, "SemanticMemory: Embeddings generated are 128-dimensional local dense vectors.");
    
    const simAB = semanticMemory.cosineSimilarity(embedA, embedB);
    const simAC = semanticMemory.cosineSimilarity(embedA, embedC);

    await assert(simAB > simAC, `SemanticMemory: Cosine similarity identifies semantic proximity (Agent vs. Agent is higher than Agent vs. Cooking). AB: ${simAB.toFixed(3)}, AC: ${simAC.toFixed(3)}`);
    console.log("");

    // ------------------------------------------------------------
    // TEST 3: Conversation Memory Logs, Pin & Archive
    // ------------------------------------------------------------
    console.log("3. Running Conversation Memory log tests...");
    
    const sessionId = "session_test_999";
    const userMsg = conversationMemory.addMessage(sessionId, "user", "I prefer using TypeScript for AI architectures.", "user_alpha");
    const aiMsg = conversationMemory.addMessage(sessionId, "model", "Acknowledged. We will structure our multi-agent framework in strict TypeScript.", "user_alpha");

    await assert(userMsg.type === "conversation", "ConversationMemory: User message saved under conversation type.");
    await assert(userMsg.sessionId === sessionId, "ConversationMemory: Correct sessionId attached.");

    const history = conversationMemory.getHistory(sessionId);
    await assert(history.length === 2, "ConversationMemory: Successfully retrieved full session chronological logs.");
    await assert(history[0].content.includes("[USER]"), "ConversationMemory: chronological sequence correctly preserves user first.");

    // Pinning
    const pinnedNode = conversationMemory.pin(userMsg.id);
    await assert(pinnedNode !== undefined && pinnedNode.type === "pinned", "ConversationMemory: Pinning changes node type to pinned.");
    await assert(pinnedNode?.importance === 10, "ConversationMemory: Pinned items are given max importance priority.");

    // Archiving
    const archivedNode = conversationMemory.archive(aiMsg.id);
    await assert(archivedNode !== undefined && archivedNode.type === "archived", "ConversationMemory: Archiving transforms node to archived state.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 4: Workflow Steps & Execution History Tracking
    // ------------------------------------------------------------
    console.log("4. Running Workflow State tracking tests...");
    
    const workflowId = "flow_agent_compilation_101";
    workflowMemory.logStep({
      stepId: "step_planning",
      workflowId,
      title: "Plan Architecture",
      description: "Analyze system and compose memory schemas.",
      status: "completed",
      timestamp: new Date(),
    });

    workflowMemory.logStep({
      stepId: "step_build",
      workflowId,
      title: "Compile Codebase",
      description: "Synthesize schemas to file components.",
      status: "failed",
      error: "Type error: Missing parameters in constructor.",
      timestamp: new Date(),
    });

    const flowSteps = workflowMemory.getSteps(workflowId);
    await assert(flowSteps.length === 2, "WorkflowMemory: Saved steps are recorded and retrievable.");
    await assert(flowSteps[1].metadata.status === "failed", "WorkflowMemory: Step execution results are preserved in metadata.");

    const failures = workflowMemory.getFailures();
    await assert(failures.length >= 1, "WorkflowMemory: Failed steps query correctly extracts failed tasks.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 5: Knowledge Graph Entity Relations & BFS Traversal
    // ------------------------------------------------------------
    console.log("5. Running Knowledge Graph & Relationship tests...");
    
    // Nodes for graph link tests
    const userNode = memoryStore.save({ type: "knowledge", content: "Developer Alpha Profile Details" });
    const convNode = memoryStore.save({ type: "conversation", content: "Developer session exploring memory maps." });
    const fileNode = memoryStore.save({ type: "knowledge", content: "File schema definition: types.ts" });

    memoryGraph.addEdge(userNode.id, convNode.id, "USER_HAD_CONVERSATION", 0.9);
    memoryGraph.addEdge(convNode.id, fileNode.id, "CONVERSATION_HAS_FILE", 0.85);

    const outgoing = memoryGraph.getOutgoing(userNode.id);
    await assert(outgoing.length === 1 && outgoing[0].relation === "USER_HAD_CONVERSATION", "MemoryGraph: Correct outgoing edges logged.");

    const incoming = memoryGraph.getIncoming(fileNode.id);
    await assert(incoming.length === 1 && incoming[0].relation === "CONVERSATION_HAS_FILE", "MemoryGraph: Correct incoming edges logged.");

    const paths = memoryGraph.traverse(userNode.id, 2);
    await assert(paths.length === 2, "MemoryGraph: Multihop traverse finds distant connections (User -> Conversation -> File).");
    await assert(paths.some((p) => p.id === fileNode.id), "MemoryGraph: Graph correctly traces indirect relationships.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 6: Memory Ranker Multi-Criteria Scoring
    // ------------------------------------------------------------
    console.log("6. Running Multi-Criteria Memory Ranker tests...");
    
    const candidateNodes = [
      memoryStore.save({ type: "long", content: "System preferences for typescript", importance: 9, usageCount: 5 }),
      memoryStore.save({ type: "long", content: "Random un-important memo content", importance: 2, usageCount: 0 }),
    ];

    const ranked = memoryRanker.rank(candidateNodes, undefined, "typescript");
    await assert(ranked[0].node.content.includes("typescript"), "MemoryRanker: Highest relevance content ranked first.");
    await assert(ranked[0].score > ranked[1].score, "MemoryRanker: Scoring algorithm mathematically prioritizes importance, relevance, and usage.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 7: Memory Retriever Pipeline (Unified Semantic Search)
    // ------------------------------------------------------------
    console.log("7. Running Memory Retriever Pipeline tests...");
    
    const targetNode = memoryStore.save({
      type: "long",
      content: "Exclusive specific token: X-RAY-LAMBDA",
      tags: ["lambda-test"],
      importance: 8,
    });

    const retrieved = await memoryRetriever.retrieve({
      text: "X-RAY-LAMBDA",
      type: "long",
    });

    await assert(retrieved.length >= 1, "MemoryRetriever: Unified search returns matching targets.");
    await assert(retrieved[0].content.includes("X-RAY-LAMBDA"), "MemoryRetriever: Semantic search accurately matches target item.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 8: Memory Compressor (Summarization and Fact Extraction)
    // ------------------------------------------------------------
    console.log("8. Running Memory Compressor tests...");
    
    const compSessionId = "session_compression_test_001";
    conversationMemory.addMessage(compSessionId, "user", "I am planning to launch a multi-agent system tomorrow.");
    conversationMemory.addMessage(compSessionId, "model", "Excellent planning. I recommend preparing the typescript memory store first.");

    const compressed = await memoryCompressor.compressSession(compSessionId);
    await assert(compressed !== undefined, "MemoryCompressor: Session logs compressed successfully.");
    await assert(compressed.content.includes("[COMPRESSED SESSION CONTEXT]"), "MemoryCompressor: Compiled compressed metadata preserved.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 9: Context Builder System Prompt Compilation
    // ------------------------------------------------------------
    console.log("9. Running Context Builder Prompt Compilation tests...");
    
    const contextSessionId = "session_context_987";
    conversationMemory.addMessage(contextSessionId, "user", "Remember my favorite programming language is Rust.");

    const contextResult = await contextBuilder.build({
      sessionId: contextSessionId,
      currentPrompt: "Tell me how to write code",
    });

    await assert(contextResult.formattedContext.includes("COGNITIVE CONTEXT BLOCK"), "ContextBuilder: Formatted header block compiled.");
    await assert(contextResult.items.length >= 1, "ContextBuilder: Extracted context elements preserved in analytical list.");
    console.log("");

    // ------------------------------------------------------------
    // TEST 10: Memory Engine Top-Level Facade
    // ------------------------------------------------------------
    console.log("10. Running Top-Level Memory Engine Facade tests...");
    
    await memoryEngine.initialize({ cacheTTLMs: 10000 });
    const manager = memoryEngine.getManager();
    await assert(manager !== undefined, "MemoryEngine: Subsystem interfaces retrieved successfully.");
    console.log("");

    console.log("============================================================");
    console.log("ALL UNIVERSAL MEMORY TESTS PASSED SUCCESSFULLY!");
    console.log("============================================================\n");
  } catch (err: any) {
    console.error(`\n❌ TEST SUITE FAILURE: ${err.message}`);
    console.error(err.stack);
    throw err;
  }
}
